### ISSUE TITLE
#01

### ISSUE THREAD

**Issue by phmiranda** [alura-cursos/fundamentos-android-parte-1#2]
Bom dia @alexfelipe , tudo bem ?
Gostaria de tirar uma dúvida quando a deploy de aplicatvo na Playstore. Conhece alguma tutorial para automatizar essa implantação quando o repositório remoto (gitlab ou github) receber novos commites na master ?

**Comment by alexfelipe** [comment]
Oi Pedro de boas e vc?
Por eu não manter um App na playstore eu não consigo te passar com precisão um tutorial 100%. Porém, eu conversei com um amigo meu que mantém apps e sugeriu os seguintes artigos:

- https://medium.com/@niraj_prajapati/automate-android-app-publishing-on-play-store-using-github-actions-554de7801c36
- https://andresand.medium.com/android-release-with-fastlane-ff0a5d2ef73f

Uma coisa que ele destacou, é importante identificar quais serão as ferramentas que vai utilizar para fazer o CI/CD para facilitar as buscas do que precisa. Veja o que acha e me passa um feedback ;)

**Comment by phmiranda** [comment]
Bacana @alexfelipe , vou olhar com calma depois. Quero automatizar tanto as publicações com Android, como React Native e é difícil encontrar algo mais detalhada step-by-step até então.
